// Generated by CoffeeScript 1.7.1
(function() {
    window._gaq = window._gaq || [];

    window._gaq.push(["_setAccount", "UA-49167525-1"]);

    if (!localStorage.first) {
        chrome.tabs.create({
            url: chrome.extension.getURL("html/intro.html")
        });
        localStorage.first = "true";
        window._gaq.push(["_trackPageview"]);
    }

    (function() {
        var ga, s;
        ga = document.createElement("script");
        ga.type = "text/javascript";
        ga.async = true;
        ga.src = "https://ssl.google-analytics.com/ga.js";
        s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(ga, s);
    })();

    chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
        if (request.page != null) {
            _gaq.push(["_set", "title", request.title]);
            return window._gaq.push(["_trackPageview", request.page]);
        }
    });

}).call(this);